name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cimg/python:3.9-node
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt update && sudo apt install bundler
    - run: bundle install
    - run: pip install -r requirements.txt
    - run: python sitebuilder.py build
    - run: ./deploy.sh
